# This is a basic workflow to help you get started with Actions

name: Arduino Deploy

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout oratek-samd-boards"
        uses: actions/checkout@v2
        with:
          path: oratek-samd-boards

      - name: Checkout json
        uses: actions/checkout@v2
        with:
          repository: oratek-ch/arduino-boards-manager
          token: ${{secrets.PAT}} # `GitHub_PAT` is a secret that contains your PAT
          path: arduino-boards-manager
          
      # Runs a single command using the runners shell
      - name: Run deploy script
        run: ./oratek-samd-boards/.github/workflows/deploy-samd-ubuntu.sh